### ISSUE TITLE
spartial functions in mysql 8

### ISSUE THREAD

**Issue by byte-bitch** [sjaakp/yii2-spatial#1]
Hi,
as you can read at https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-0.html#mysqld-8-0-0-spatial-support the mysql functions X(), Y() are GeomFromText() are removed. The new functions are called ST_X(), ST_Y() and ST_GeomFromText().

Is it possible to add support for mysql 8?

Greetings Chris

**Comment by acorncom** [comment]
This was resolved in the MySQL 5.7 patch
