### ISSUE TITLE
Which MySQL version is this for?

### ISSUE THREAD

**Issue by gvanto** [sjaakp/yii2-spatial#2]
Firstly thanks great library.

When i run a ->nearest() on my new spatialmodel, I get the following SQL created, but it causes an error in MySQL 5.7.25:

`SELECT *, 111.045*DEGREES(ACOS(COS(RADIANS('-34.06176630'))*COS(RADIANS(_lat))*COS(RADIANS('18.82098640')-RADIANS(_lng))+SIN(RADIANS('-34.06176630'))*SIN(RADIANS(_lat)))) AS `_d`, AsText(geo_point) AS geo_point FROM (SELECT *, X(geo_point) AS `_lng`, Y(geo_point) AS `_lat` FROM `location` HAVING (`_lng` BETWEEN 17.733952878026 AND 19.908019921974) AND (`_lat` BETWEEN -34.962302118812 AND -33.161230481188)) `0` HAVING `_d` < 100 ORDER BY `_d``

**Comment by sjaakp** [comment]
Hello Gert,

 

Well, you got me. Yii2-spatial was developed when MySQL 5.6 was around. It used functions that where deprecated in 5.7 and apparently disappeared in the latest minor versions. Luckily for me it boils down to some function name changes. I just uploaded a new version of Yii2-spatial that should resolve the issue.

 

Thanks for pointing this out,

Sjaak

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: Gert <notifications@github.com> 
Verzonden: maandag 1 april 2019 16:26
Aan: sjaakp/yii2-spatial <yii2-spatial@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-spatial] Which MySQL version is this for? (#2)

 

Firstly thanks great library.

When i run a ->nearest() on my new spatialmodel, I get the following SQL created, but it causes an error in MySQL 5.7.25:

SELECT *, 111.045*DEGREES(ACOS(COS(RADIANS('-34.06176630'))*COS(RADIANS(_lat))*COS(RADIANS('18.82098640')-RADIANS(_lng))+SIN(RADIANS('-34.06176630'))*SIN(RADIANS(_lat)))) AS _d, AsText(geo_point) AS geo_point FROM (SELECT *, X(geo_point) AS _lng, Y(geo_point) AS _latFROMlocation HAVING (_lng BETWEEN 17.733952878026 AND 19.908019921974) AND (_latBETWEEN -34.962302118812 AND -33.161230481188))0HAVING_d< 100 ORDER BY_d``

**Comment by gvanto** [comment]
Great @sjaakp thanks for the fix!

**Comment by acorncom** [comment]
Looks like this issue can be closed?
